import type { Metadata } from "next";
import "../app/globals.css";
import Nav from "./Components/Nav";

export const metadata: Metadata = {
  title: "Aike",
  description: "Generated by Aike",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Nav />
        {children}
      </body>
    </html>
  );
}
