// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import Nav from "./Components/Nav";
import Footer from "./Components/Footer";
import { AppProvider } from "./contexts/AppContext";

export const metadata: Metadata = {
  title: "Aike",
  description: "Generated by Aike",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AppProvider>
          {" "}
          {/* Wrap the app with the context provider */}
          <Nav />
          {children}
          <Footer />
        </AppProvider>
      </body>
    </html>
  );
}
